### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by AldeVrs** [JunkyBulgaria/FusionCMS#2]
Eyh !
I've installed succesfuly the template 'til I received this error.

A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: /home/www/models/external_account_model.php
Line Number: 386

Possible to add this 'models' files in the main code ? Thanks.

**Comment by JunkyBulgaria** [comment]
that's your problem, cms works just fine, probably your settings aren't configured properly
